apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../05-applications/hello-app/deployment.yaml
  - ../../../05-applications/hello-app/service.yaml
  - ../../../05-applications/hello-app/ingress.yaml
  - ../../../05-applications/hello-app/canary.yaml
  - ../../../cluster/kind-cluster/infrastructure.yaml