apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devops-lab-app-cert
  namespace: lab-test
spec:
  secretName: devops-lab-app-tls-secret
  dnsNames:
  - lab.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer